name: ORION Event Test

on:
  workflow_dispatch:

jobs:
  event-test:
    runs-on: ubuntu-latest

    steps:
      - name: 코드 가져오기
        uses: actions/checkout@v4

      - name: 파이썬 설치
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: 라이브러리 설치
        run: pip install -r requirements.txt

      - name: 이벤트 테스트 실행
        run: python orion_event_test.py
